version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1435:1433"
    environment:
      - SA_PASSWORD=Abcdefg*12345678910!
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver-data:/var/opt/mssql